#!/bin/sh
# This script will install all files in IntelliJ IDEA's lib/ folder to the local maven .m2 repository. This way we can use them during the build
#
# Usage:
#   ./install-intellij-libs.sh 13.1.4 /Users/ahe/Applications/IntelliJ-IDEA-13.app/

IDEA_VERSION=$1
INTELLIJ_HOME=$2

if [ -z "$INTELLIJ_HOME" ]
then
  echo "Please provide the version and path to the IntelliJ home directory. For example: ./install-intellij-libs.sh 13.1.4 /Users/ahe/Applications/IntelliJ-IDEA-13.app/"
  exit 1
fi

if [ ! -d "$INTELLIJ_HOME" ]
then
  echo "Directory does not exist: $INTELLIJ_HOME"
  exit 1
fi

echo 'Installing IntelliJ artifacts to Maven local repository'
echo "IntelliJ home: $INTELLIJ_HOME"
for artifact in openapi idea extensions annotations util forms_rt
do
	path="$INTELLIJ_HOME/lib/$artifact.jar"
	if [ -f "$path" ]
	then
		echo installing $artifact ${IDEA_VERSION} from  $path
		mvn install:install-file -Dfile="$path" -DgroupId=com.intellij -DartifactId=$artifact -Dversion=${IDEA_VERSION} -Dpackaging=jar
	else
		echo $artifact does not exist at $path
	fi
done

